### ISSUE TITLE
To fix guest issue

### ISSUE THREAD

**Issue by TechWhizZ199** [notnola/pinychat#16]
It seems that once a guest has joined, someone who is not using an account, if they set their nick as something other than that they joined in with, the messaging functions seem to work again. This might be a fix to the issue, however I am not completely sure about it.

**Comment by swiftSwathSee** [comment]
Not sure what guest issue you're referring to. The only messaging issue I know of is a rare one where for some reason certain nicks can't receive PMs from you, but no one's opened an issue for it yet.

**Comment by TechWhizZ199** [comment]
I was just saying that sometimes you cannot send a message once you have just joined the room as a guest. For some reason once you change your nickname manually, you can start sending messages.

**Comment by swiftSwathSee** [comment]
By guest, do you just mean a non-account user? Because this issue doesn't exist, or at least it doesn't when using the library instead of the bot. You might have just been seeing the usual connection issue that Tinychat's servers occasionally have, whereby the connection only works after a ton of retries (even on the Flash client). This very issue actually was actually particularly bad this week, but Tinychat seems to have finally fixed it like 24 hours ago.

**Comment by TechWhizZ199** [comment]
Yes, I believe the issue I stated does not exist anymore but there is the issue with the client not connecting and after several retries it does, like you said. Thank you anyway Swift.

**Comment by TechWhizZ199** [comment]
No longer an issue.
