### ISSUE TITLE
Need a better way to detect current video

### ISSUE THREAD

**Issue by swiftSwathSee** [notnola/pinychat#25]
Doing `/playyoutube @` normally opens the current video in a browser. The problem is that the current video is only identified if the module sees someone play it (i.e. the server message `/mbs [videoID]`). So if you join a room and a video is already playing, the module thinks that no video is playing, because the server doesn't send that `/mbs` upon connecting.

Meaning, there needs to be a way to detect the currently-playing video at connection time.

**Comment by nortxort** [comment]
Actually a /mbs message is sent upon joining a room that has a youtube/soundcloud playing. It is sent from the client playing the youtube/soundcloud

**Comment by TechWhizZ199** [comment]
It does send this message for normal users (moderators). However videos which are played by the bot has never been able to played back to users who join afterwards. This is the reason why a lot modules store the videos local time and send a user specific message for the video upon joining. If we can figure out why the message does not send for bots, maybe we can get the server to load videos which the bot has played.

**Comment by ghost** [comment]
This was fixed by TechWhizZ199 sending the media information via a "undercover message". 

Something like this: 

`def send_undercover_msg(self, nick, msg):
        self._sendCommand('privmsg', [u"" + self._encodeMessage(msg), "#0,en", u"b" + str(user.id) + '-' + nick])`

And sending the media info with said message to the new user upon nick change

`self.send_undercover_msg(new, '/mbs ' + self.type_media + ' ' + self.video_id + ' ' + str(self.elapsed_track_time))`

Undercover: https://github.com/TechWhizZ199/pinybot/blob/master/tinychat.py#L835
Sending media info: https://github.com/TechWhizZ199/pinybot/blob/master/pinybot.py#L278

Though he is keeping track of the media time for playlist functionality. May be worth looking into either way.

**Comment by TechWhizZ199** [comment]
pinybot will be updated at https://github.com/GoelBiju/pinybot

If you need anything else it will be there.
