### ISSUE TITLE
Indication for incorrect login details

### ISSUE THREAD

**Issue by swiftSwathSee** [notnola/pinychat#46]
When the username and password are wrong, there is no obvious indication. It just connects, then crashes after you try to send more than one message. A similar (or possibly the same) thing happens when you connect to a room you've been banned from (see #36).

**Comment by nortxort** [comment]
I don't quite understand why you insist on using this lib..Most of the problems your dealing with have already been solved in other projects, so it's a bit like trying to reinvent the wheel.

Anyway, there is no check to see if account and password have been provided before trying to login with __authHTTP, it just tries to log you in when you initiate the class.
On line 1072 in __authHTTP you have raw. raw.cookies contains the cookies(if any) from the login POST, so you could check to see if the correct cookie(s) are there or not. 

Also, on side note. You could merge the 2 methods __getAutoOp and __getProHash in to one method as they both make a request to the same URL. But since tinychat changed the way you connect, you don't even need this anymore, just change the way you connect.

**Comment by TechWhizZ199** [comment]
I am in support of nortxort's comment here. It is almost futile working with a library that is outdated by a lot of versions (when there are other libraries which are updated). It might be wise to consider merging the project with existing libraries, then we can all contribute to one main project.
